// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAlert = `-- name: GetAlert :one
SELECT id, rule_id, transaction_id, status, severity, created_at, updated_at
FROM alerts
WHERE id = $1
`

func (q *Queries) GetAlert(ctx context.Context, id pgtype.UUID) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlert, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.TransactionID,
		&i.Status,
		&i.Severity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAlertIfAbsent = `-- name: InsertAlertIfAbsent :one
INSERT INTO alerts (rule_id, transaction_id, severity)
VALUES ($1, $2, $3)
ON CONFLICT (rule_id, transaction_id) DO NOTHING
RETURNING id, rule_id, transaction_id, status, severity, created_at, updated_at
`

type InsertAlertIfAbsentParams struct {
	RuleID        pgtype.UUID `json:"rule_id"`
	TransactionID pgtype.UUID `json:"transaction_id"`
	Severity      string      `json:"severity"`
}

// Idempotent raise: a given (rule, transaction) yields at most one alert. On
// conflict no row is returned, so the caller can skip emitting a duplicate event.
func (q *Queries) InsertAlertIfAbsent(ctx context.Context, arg InsertAlertIfAbsentParams) (Alert, error) {
	row := q.db.QueryRow(ctx, insertAlertIfAbsent, arg.RuleID, arg.TransactionID, arg.Severity)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.TransactionID,
		&i.Status,
		&i.Severity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlertsAfterCursor = `-- name: ListAlertsAfterCursor :many
SELECT id, rule_id, transaction_id, status, severity, created_at, updated_at
FROM alerts
WHERE ($1::text IS NULL OR status = $1)
  AND (created_at < $2
       OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAlertsAfterCursorParams struct {
	Status          *string            `json:"status"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

func (q *Queries) ListAlertsAfterCursor(ctx context.Context, arg ListAlertsAfterCursorParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsAfterCursor,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.TransactionID,
			&i.Status,
			&i.Severity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsFirstPage = `-- name: ListAlertsFirstPage :many
SELECT id, rule_id, transaction_id, status, severity, created_at, updated_at
FROM alerts
WHERE ($1::text IS NULL OR status = $1)
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListAlertsFirstPageParams struct {
	Status    *string `json:"status"`
	PageLimit int32   `json:"page_limit"`
}

func (q *Queries) ListAlertsFirstPage(ctx context.Context, arg ListAlertsFirstPageParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsFirstPage, arg.Status, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.TransactionID,
			&i.Status,
			&i.Severity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlertStatus = `-- name: UpdateAlertStatus :one
UPDATE alerts
SET status = $1, updated_at = now()
WHERE id = $2 AND status = $3
RETURNING id, rule_id, transaction_id, status, severity, created_at, updated_at
`

type UpdateAlertStatusParams struct {
	NewStatus     string      `json:"new_status"`
	ID            pgtype.UUID `json:"id"`
	CurrentStatus string      `json:"current_status"`
}

// Conditional update guards against lost updates: it only transitions when the
// current status matches. Zero rows means a stale/!concurrent transition.
func (q *Queries) UpdateAlertStatus(ctx context.Context, arg UpdateAlertStatusParams) (Alert, error) {
	row := q.db.QueryRow(ctx, updateAlertStatus, arg.NewStatus, arg.ID, arg.CurrentStatus)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.TransactionID,
		&i.Status,
		&i.Severity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
