// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rules.sql

package db

import (
	"context"
)

const insertRuleIfAbsent = `-- name: InsertRuleIfAbsent :exec
INSERT INTO rules (name, field, operator, value, severity, enabled)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (name) DO NOTHING
`

type InsertRuleIfAbsentParams struct {
	Name     string `json:"name"`
	Field    string `json:"field"`
	Operator string `json:"operator"`
	Value    string `json:"value"`
	Severity string `json:"severity"`
	Enabled  bool   `json:"enabled"`
}

func (q *Queries) InsertRuleIfAbsent(ctx context.Context, arg InsertRuleIfAbsentParams) error {
	_, err := q.db.Exec(ctx, insertRuleIfAbsent,
		arg.Name,
		arg.Field,
		arg.Operator,
		arg.Value,
		arg.Severity,
		arg.Enabled,
	)
	return err
}

const listEnabledRules = `-- name: ListEnabledRules :many
SELECT id, name, field, operator, value, severity, enabled, created_at
FROM rules
WHERE enabled = TRUE
ORDER BY created_at, id
`

func (q *Queries) ListEnabledRules(ctx context.Context) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listEnabledRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Field,
			&i.Operator,
			&i.Value,
			&i.Severity,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
