// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (aggregate, event_type, payload, occurred_at)
VALUES ($1, $2, $3, $4)
`

type InsertOutboxEventParams struct {
	Aggregate  string             `json:"aggregate"`
	EventType  string             `json:"event_type"`
	Payload    []byte             `json:"payload"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.Aggregate,
		arg.EventType,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (account_id, amount_minor, currency, direction, status, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, account_id, amount_minor, currency, direction, status, occurred_at, created_at
`

type InsertTransactionParams struct {
	AccountID   string             `json:"account_id"`
	AmountMinor int64              `json:"amount_minor"`
	Currency    string             `json:"currency"`
	Direction   string             `json:"direction"`
	Status      string             `json:"status"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.AccountID,
		arg.AmountMinor,
		arg.Currency,
		arg.Direction,
		arg.Status,
		arg.OccurredAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AmountMinor,
		&i.Currency,
		&i.Direction,
		&i.Status,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactionsAfterCursor = `-- name: ListTransactionsAfterCursor :many
SELECT id, account_id, amount_minor, currency, direction, status, occurred_at, created_at
FROM transactions
WHERE occurred_at < $1
   OR (occurred_at = $1 AND id < $2)
ORDER BY occurred_at DESC, id DESC
LIMIT $3
`

type ListTransactionsAfterCursorParams struct {
	CursorOccurredAt pgtype.Timestamptz `json:"cursor_occurred_at"`
	CursorID         pgtype.UUID        `json:"cursor_id"`
	PageLimit        int32              `json:"page_limit"`
}

// Expanded keyset predicate (not a row-value comparison) so sqlc infers the
// correct column types: occurred_at is timestamptz, id is uuid.
func (q *Queries) ListTransactionsAfterCursor(ctx context.Context, arg ListTransactionsAfterCursorParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsAfterCursor, arg.CursorOccurredAt, arg.CursorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.AmountMinor,
			&i.Currency,
			&i.Direction,
			&i.Status,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsFirstPage = `-- name: ListTransactionsFirstPage :many
SELECT id, account_id, amount_minor, currency, direction, status, occurred_at, created_at
FROM transactions
ORDER BY occurred_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListTransactionsFirstPage(ctx context.Context, limit int32) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsFirstPage, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.AmountMinor,
			&i.Currency,
			&i.Direction,
			&i.Status,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
